// Generated by CoffeeScript 1.6.3
(function() {
  exports.makeSuffix = function(fileName, suffix) {
    var suffixIdx;
    if ((suffix.indexOf(".")) === -1) {
      suffix = "." + suffix;
    }
    suffixIdx = fileName.lastIndexOf(".");
    if (suffixIdx === -1) {
      return fileName + suffix;
    } else {
      if (suffix.toLowerCase() === (fileName.substring(suffixIdx)).toLowerCase()) {
        return fileName;
      } else {
        return fileName + suffix;
      }
    }
  };

}).call(this);
